# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metrics.proto',
  package='models',
  syntax='proto3',
  serialized_pb=_b('\n\rmetrics.proto\x12\x06models\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n\x0cHistogramBin\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\r\n\x05start\x18\x02 \x01(\x01\x12\x0e\n\x06length\x18\x03 \x01(\x01\"s\n\tHistogram\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x04\x62ins\x18\x02 \x03(\x0b\x32\x14.models.HistogramBin\x12\x34\n\x10measurement_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_HISTOGRAMBIN = _descriptor.Descriptor(
  name='HistogramBin',
  full_name='models.HistogramBin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='models.HistogramBin.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='models.HistogramBin.start', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='models.HistogramBin.length', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=118,
)


_HISTOGRAM = _descriptor.Descriptor(
  name='Histogram',
  full_name='models.Histogram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='models.Histogram.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bins', full_name='models.Histogram.bins', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurement_time', full_name='models.Histogram.measurement_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=235,
)

_HISTOGRAM.fields_by_name['bins'].message_type = _HISTOGRAMBIN
_HISTOGRAM.fields_by_name['measurement_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['HistogramBin'] = _HISTOGRAMBIN
DESCRIPTOR.message_types_by_name['Histogram'] = _HISTOGRAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HistogramBin = _reflection.GeneratedProtocolMessageType('HistogramBin', (_message.Message,), dict(
  DESCRIPTOR = _HISTOGRAMBIN,
  __module__ = 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:models.HistogramBin)
  ))
_sym_db.RegisterMessage(HistogramBin)

Histogram = _reflection.GeneratedProtocolMessageType('Histogram', (_message.Message,), dict(
  DESCRIPTOR = _HISTOGRAM,
  __module__ = 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:models.Histogram)
  ))
_sym_db.RegisterMessage(Histogram)


# @@protoc_insertion_point(module_scope)
